#!/usr/bin/python
###############################################################################
# Export Box Mask
#
# This post action will export the box mask of all cleaned images along with
# the rest of the things being exported. Images that get split into multiple
# segments by Panel Cleaner are also supported.
#
# Important: Use a profile that has the option "Always Cache Masks" enabled,
#            otherwise the box mask will not be generated and this script will
#            fail to find it. This option is in the General tab of the profile
#            settings. (Added in 2.11.11)
#
# Set the command to the following in the Post-Action Configuration:
#   python ~/Downloads/ExportBoxMask.py --output-files %o --cache-ids %c
#
# Note: Be sure to update the path to point to the location of this script
#
# It needs the output file paths %o and the cache uuids %c to find the correct
# box mask for each image, in case there are multiple images with the same name
# in different directories.
#
# Python packages required: None
#
# Script version 1.0
###############################################################################
# Configuration. Modify before use:

# Modify the cache dir path to fit your system. The default is for Linux and is different on Windows and MacOS.
# In the GUI, press "Open Log" in the bottom right corner and look for the line that says (on Linux):
# Cache directory: /home/<username>/.cache/pcleaner
# Replace the placeholder <username> with your actual username.
CACHE_DIR = "~/.cache/pcleaner"

# To diagnose issues, set a log path. Disable this by setting it to None.
LOG_PATH = None
# LOG_PATH = "~/Desktop/ExportBoxMask.log"

# The file name endings to look for when searching for the box mask.
# Adding more endings will copy additional files, not just the box mask, if you wish to do so.
# You must check that this output is actually being generated by the cleaner, otherwise it will fail to find the file.
# Not all are by default.
EXPORT_FILES_ENDING_IN = ["_box_mask.png"] #, "_noise_mask.png"]

################################################################################
# Script internals. Modify at your own risk.
from pathlib import Path
import argparse
import logging
import shutil

logger = logging.getLogger("ExportBoxMask")


# This lets the argparse errors appear in the log file.
class LoggingArgumentParser(argparse.ArgumentParser):
    def error(self, message):
        logger.error("Argument parse error: %s", message)
        logger.debug("Usage: %s", self.format_usage().strip())
        super().error(message)


def setup_logging():
    handlers: list[logging.Handler] = [logging.StreamHandler()]

    if LOG_PATH is not None:
        log_path = Path(LOG_PATH).expanduser().absolute()
        log_path.parent.mkdir(parents=True, exist_ok=True)
        handlers.append(logging.FileHandler(log_path, encoding="utf-8"))

    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        handlers=handlers,
        force=True,
    )


def parse_arguments():
    # The script expects two arguments: the output file paths and the cache uuids.
    try:
        # Using color in the log file doesn't work.
        parser = LoggingArgumentParser(description="Export Box Mask", color=False)
    except TypeError:
        parser = LoggingArgumentParser(description="Export Box Mask")

    parser.add_argument(
        "--output-files", nargs="+", required=True, dest="output_files", help="Output file paths"
    )
    parser.add_argument(
        "--cache-ids", nargs="+", required=True, dest="cache_ids", help="Cache UUIDs"
    )
    return parser.parse_args()


def main():
    setup_logging()
    logger.info("--- Starting ExportBoxMask.py ---")

    args = parse_arguments()

    logger.debug("Output files: %s", args.output_files)
    logger.debug("Cache IDs: %s", args.cache_ids)

    # Sanity check: Ensure the number of output files matches the number of cache IDs.
    if len(args.output_files) != len(args.cache_ids):
        raise ValueError(
            f"Expected the same number of output files and cache IDs, "
            f"got {len(args.output_files)} output files and {len(args.cache_ids)} cache IDs."
        )

    cache_dir = Path(CACHE_DIR).expanduser().absolute() / "cleaner"
    logger.debug("Cache directory: %s", cache_dir)

    # Loop through each output file and its corresponding cache ID to find and copy the desired outputs.
    for output_file, cache_id in zip(args.output_files, args.cache_ids):
        output_parent = Path(output_file).parent
        # Because file extensions can be silly, we will do the robust thing and just look for the file that
        # starts with the cache ID and ends with one of the specified endings.
        found_one = False
        for file in cache_dir.glob(f"{cache_id}*"):
            if any(file.name.endswith(ending) for ending in EXPORT_FILES_ENDING_IN):
                filename_no_uuid = file.name.split(cache_id + "_", 1)[
                    -1
                ]  # Remove the cache ID and the underscore prefix from the filename.
                output_path = output_parent / filename_no_uuid
                # Copy the file to the output path, replacing any existing file.
                shutil.copy(file, output_path)
                logger.info("Exported %s to %s", file, output_path)
                found_one = True
        if not found_one:
            logger.error(
                "No matching file found for %s cache ID %s in cache directory %s",
                output_file,
                cache_id,
                cache_dir,
            )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("Error in ExportBoxMask.py")
        # Re-raise the exception in case this is running in a terminal.
        raise
